name: Manual Auto Comment

on:
  issue_comment:
    types: [created]

jobs:
  add-auto-comment:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '@auto-comment')

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Add automated comment to PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This is a sample prompt triggered by @auto-comment'
            })
