name: Manual Auto Comment

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [labeled]

jobs:
  add-auto-comment:
    if: |
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request &&
       contains(github.event.comment.body, '@auto-comment')) ||
      (github.event_name == 'pull_request' &&
       github.event.label.name == 'auto-comment')

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Add reaction to acknowledge comment
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            })

      - name: Set PR number
        id: pr-number
        run: |
          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            echo "number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          else
            echo "number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Add automated comment to PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.pr-number.outputs.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This is a sample prompt triggered by @auto-comment or the auto-comment label'
            })
